name: Docker build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: martinbeentjes/npm-get-version-action@main
        id: package-version

      - name: Build and optionally push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: |
            ghcr.io/filecoin-station/core
            ghcr.io/filecoin-station/core:${{ steps.package-version.outputs.current-version }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/filecoin-station/core
          cache-to: type=inline

      # - name: Start Station Core container
      #   run: |
      #     docker run \
      #       --name station \
      #       --detach \
      #       --env FIL_WALLET_ADDRESS=f1abjxfbp274xpdqcpuaykwkfb43omjotacm2p3za \
      #       $IMAGEID
      #   env:
      #     IMAGEID: ${{ steps.docker_build.outputs.imageid }}

      # - name: Verify container activity
      #   run: |
      #     LOGS=$(docker exec station bin/station.js activity)
      #     echo $LOGS
      #     echo $LOGS | grep "Saturn module started"
      #     echo $LOGS | grep "Module Runtime started"

